version: '3'
services:
  workspace:
    command: sleep infinity
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: volume
        source: workspace_node_modules
        target: /workspace/node_modules
    working_dir: /workspace
volumes:
  workspace_node_modules:
